
<script src='<%=Page.ResolveClientUrl("~/resources/js/common/jquery.js")%>' type="text/javascript"></script>
<script src='<%=Page.ResolveClientUrl("~/resources/js/common/jquery-ui.js")%>' type="text/javascript"></script>

<link rel="stylesheet" type="text/css" href="<%=Page.ResolveClientUrl("~/resources/js/common/jquery-ui.css")%>"/>   
<link rel="stylesheet" type="text/css" href="<%=Page.ResolveClientUrl("~/resources/megamenu-js-master/css/style.css")%>"/>
<link rel="stylesheet" type="text/css" href="<%=Page.ResolveClientUrl("~/resources/megamenu-js-master/css/ionicons.min.css")%>"/>
<link rel="stylesheet" type="text/css" href="<%=Page.ResolveClientUrl("~/resources/js/common/jquery-ui.theme.css")%>"/>
<link rel="stylesheet" type="text/css" href="<%=Page.ResolveClientUrl("~/resources/datatables/css/jquery.dataTables_themeroller.css")%>"/>
<link rel="stylesheet" type="text/css" href="<%=Page.ResolveClientUrl("~/resources/datatables/css/jquery.dataTables.css")%>"/>
<link rel="stylesheet" type="text/css" href="<%=Page.ResolveClientUrl("~/resources/css/global_web.css")%>"/>